### ISSUE TITLE
member.user.displayAvatarURL is not a function at CanvasSenpai.welcome (DONE)

### ISSUE THREAD

**Issue by Wykz** [CTK-WARRIOR/canvas-senpai#1]
(node:58) UnhandledPromiseRejectionWarning: TypeError: member.user.displayAvatarURL is not a function
at CanvasSenpai.welcome (/home/container/node_modules/canvas-senpai/src/canva.js:69:19)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async Client.<anonymous> (/home/container/index.js:74:15)
(node:58) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:58) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Version NPM : 12

Version DJS : 11.6.4

**Comment by CTK-WARRIOR** [comment]
You must be using canvas senpai in message event but it is created to be used in guildMemberAdd event.

**Comment by Wykz** [comment]
okay
