### ISSUE TITLE
Fontconfig error: Cannot load default config file

### ISSUE THREAD

**Issue by igssoap** [CTK-WARRIOR/canvas-senpai#2]
Everything is working fine, but the font not showing.

**Comment by JuicyAdde** [comment]
Are you hosting on Glitch? @igssoap 
I don't think Glitch is supporting custom fonts.

**Comment by igssoap** [comment]
Im hosting it in repl.it

**Comment by iseizuu** [comment]
honestly, i host in repli it too, and show same error, but it's still work propperly

**Comment by JuicyAdde** [comment]
Looks like repl.it doesn't support custom fonts.

**Comment by igssoap** [comment]
Any solution?

**Comment by igssoap** [comment]
Anyone?

**Comment by Agent-Mimos** [comment]
Don't host it with repl.it ezzzzz

**Comment by Yonle** [comment]
Hello boi!
Me are Hosting at Repl.it too!

Soon, at some Hosting Site such as Glitch.com/repl.it/heroku.com Isn't supporting Fonts "Yeet"

So, How to fix it???

All you need:

1. **Font Files**
_Download it at Google dude. Just select your favourite Font as you want._

2. **canvas-senpai**
You know this dude?

How to BREAK & FIX IT?

1. _Extract your .zip font file_
2. _Keep those .t** or .*** Fonts files at your Folder,_
3. __Upload to your Project__
4. __Enter your Font Files name__
5. **DONE**

PS: I didn't know does it works at _canvas-senpai_ or no. But just try it.

Goodluck.
