### ISSUE TITLE
Welcome image

### ISSUE THREAD

**Issue by Mikaru0Mystic** [CTK-WARRIOR/canvas-senpai#4]
Please make it so instead of asking for "member" we can directly put the username and discriminator, for some reasons im not able to directly give the member so im not able to use it (using Discord Bot Maker)

**Comment by zedxos** [comment]
Can you add an option in welcome that has text ‘Welcome’ in the img?

**Comment by Yonle** [comment]
Sorry, This npm package, is **not for DBD(Discord bot Designer)**. Also this is for [Discord.js](https://npmjs.com/discord.js) only.

Hope you understand 🙂

- Yonle

**Comment by mezotv** [comment]
> Can you add an option in welcome that has text ‘Welcome’ in the img?

can you add me on discord i can help you maybe my name is Mezo#0001
